server:
  port: 8085
  servlet:
    context-path: /ws-workplace
    application-display-name: workplace
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://vm-mgsn-as1-dev.ursip.ru:5432/activiti
    username: postgres
    password: qwerty123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: documents
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    ru.ursip.webservice.mgsn.oshs: DEBUG
    org.springframework.web: DEBUG
  file: logs/workplace.log